/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#00372d",
        "surface-tint": "#4c56af",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#000767",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eeeeee",
        "on-tertiary-fixed-variant": "#065043",
        "tertiary-fixed": "#afefdd",
        "on-surface": "#1a1c1c",
        "inverse-on-surface": "#f1f1f1",
        "primary-fixed": "#e0e0ff",
        "error": "#ba1a1a",
        "inverse-surface": "#2f3131",
        "outline": "#767683",
        "on-error-container": "#93000a",
        "on-surface-variant": "#454652",
        "surface-dim": "#dadada",
        "primary-fixed-dim": "#bdc2ff",
        "primary": "#000666",
        "background": "#f9f9f9",
        "secondary": "#006a6a",
        "on-tertiary-container": "#65a393",
        "surface-container-high": "#e8e8e8",
        "on-secondary": "#ffffff",
        "on-background": "#1a1c1c",
        "surface-container-highest": "#e2e2e2",
        "inverse-primary": "#bdc2ff",
        "tertiary": "#002019",
        "on-tertiary-fixed": "#00201a",
        "secondary-fixed-dim": "#76d6d5",
        "surface-variant": "#e2e2e2",
        "on-primary-container": "#8690ee",
        "on-primary-fixed-variant": "#343d96",
        "surface-container-low": "#f3f3f3",
        "on-secondary-fixed": "#002020",
        "surface-bright": "#f9f9f9",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#004f4f",
        "outline-variant": "#c6c5d4",
        "surface": "#f9f9f9",
        "primary-container": "#1a237e",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#94d3c1",
        "secondary-fixed": "#93f2f2",
        "secondary-container": "#90efef",
        "on-error": "#ffffff",
        "on-secondary-container": "#006e6e"
      },
      fontFamily: {
        "headline": ["Cairo", "Manrope", "sans-serif"],
        "body": ["Cairo", "Inter", "sans-serif"],
        "label": ["Cairo", "Inter", "sans-serif"],
        "sans": ["Cairo", "Inter", "sans-serif"],
        "display": ["Cairo", "Manrope", "sans-serif"],
      },
      boxShadow: {
        'ambient': '0 12px 40px rgba(0, 6, 102, 0.04)',
      },
    },
  },
  plugins: [],
}
