export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/admin/login',
    REFRESH: '/admin/refresh',
    LOGOUT: '/admin/logout',
    FORGOT_PASSWORD: '/auth/password/forgot',
  },
  DASHBOARD: {
    BASE: '/admin/dashboard',
    STATS: '/admin/dashboard/stats',
    GROWTH: '/admin/dashboard/growth',
    CITIES: '/admin/dashboard/cities',
    RECENT: '/admin/dashboard/recent',
  },
  TRIPS: {
    LIVE: '/admin/trips/live',
    ALL: '/admin/trips',
    POPULAR_ROUTES: '/admin/routes/popular',
  },
  DRIVERS: {
    ALL: '/admin/drivers',
    STATS: '/admin/drivers/stats',
    ACTIVITY: '/admin/drivers/activity',
    TOP: '/admin/drivers/top',
    DASHBOARD: '/admin/drivers/dashboard',
    VERIFICATION_EFFICIENCY: '/admin/drivers/verification-efficiency',
    PROFILE: (id: string | number) => `/admin/drivers/${id}/profile`,
    DRIVER_DASHBOARD: (id: string | number) => `/admin/drivers/${id}/dashboard`,
  },
  USERS: {
    ALL: '/admin/users',
    STATUS: (id: string | number) => `/admin/users/${id}/status`,
    BAN: (id: string | number) => `/admin/users/${id}/ban`,
    UNBAN: (id: string | number) => `/admin/users/${id}/unban`,
  },
  PASSENGERS: {
    FULL_PROFILE: (id: string | number) => `/admin/passengers/${id}/full-profile`,
    STATS: (id: string | number) => `/admin/passengers/${id}/stats`,
    MONTHLY_TRIPS: (id: string | number) => `/admin/passengers/${id}/monthly-trips`,
    RECENT_TRIPS: (id: string | number) => `/admin/passengers/${id}/recent-trips`,
    COMPLAINTS: (id: string | number) => `/admin/passengers/${id}/complaints`,
    WALLET_CHARGES: (id: string | number) => `/admin/passengers/${id}/wallet-charges`,
    CHARGE_WALLET: (id: string | number) => `/admin/passengers/${id}/charge-wallet`,
  },
  WALLET: {
    ADMIN_WALLET: '/admin/wallet',
    WALLETS: '/admin/wallets',
    TRANSACTIONS: (id: string | number) => `/admin/wallet/${id}/transactions`,
    REQUESTS: '/admin/wallet/requests',
    APPROVE_REQUEST: (id: string | number) => `/admin/wallet/requests/${id}/approve`,
    REJECT_REQUEST: (id: string | number) => `/admin/wallet/requests/${id}/reject`,
    CHARGE: '/admin/wallet/charge',
  },
  VERIFICATIONS: {
    PENDING: '/admin/verifications',
    APPROVE: (id: string | number) => `/admin/verifications/${id}/approve`,
    REJECT: (id: string | number) => `/admin/verifications/${id}/reject`,
  },
  STAFF: {
    LOGIN: '/staff/login',
    REFRESH: '/staff/refresh',
    LOGOUT: '/staff/logout',
    ME: '/staff/me',
    REVIEWS: '/staff/reviews',
    DELETE_REVIEW: (id: string | number) => `/staff/reviews/${id}`,
    USERS: '/staff/users',
    USER_PROFILE: (id: string | number) => `/staff/users/${id}`,
    TRIPS: '/staff/trips',
    CANCEL_TRIP: (id: string | number) => `/staff/trips/${id}/cancel`,
    BOOKINGS: '/staff/bookings',
    CANCEL_BOOKING: (id: string | number) => `/staff/bookings/${id}/cancel`,
    COMPLAINTS: '/staff/complaints',
    COMPLAINT: (id: string | number) => `/staff/complaints/${id}`,
    RESPOND_COMPLAINT: (id: string | number) => `/staff/complaints/${id}/respond`,
    ESCALATE_COMPLAINT: (id: string | number) => `/staff/complaints/${id}/escalate`,
    PENDING_VERIFICATIONS: '/staff/verifications/pending',
    APPROVE_VERIFICATION: (id: string | number) => `/staff/verifications/${id}/approve`,
    REJECT_VERIFICATION: (id: string | number) => `/staff/verifications/${id}/reject`,
    ESCALATED_COMPLAINTS: '/staff/escalated-complaints',
    RESOLVE_ESCALATED: (id: string | number) => `/staff/escalated-complaints/${id}/resolve`,
  },
  EMPLOYEES: {
    ALL: '/employees',
    SINGLE: (id: string | number) => `/employees/${id}`,
    TOGGLE_ACTIVE: (id: string | number) => `/employees/${id}/toggle-active`,
    RESET_PASSWORD: (id: string | number) => `/employees/${id}/reset-password`,
  },
  REPORTS: '/admin/reports',
  EXPORT_PDF: '/admin/export/pdf',
};
